# Generated by Django 5.1.4 on 2026-06-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
