# Generated by Django 5.1.4 on 2026-06-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_add_joining_expiry_to_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='subscription_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
