# Generated by Django 5.1.4 on 2026-06-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_add_subscription_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='tier',
            field=models.CharField(choices=[('TIER1', 'Basic'), ('TIER2_WA', 'WhatsApp'), ('TIER2_AT', 'Attendance'), ('TIER3', 'Pro')], default='TIER1', max_length=20),
        ),
    ]
