# Generated by Django 5.1.4 on 2026-06-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_add_gym_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gympayment',
            name='months',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
