# Generated by Django 5.1.4 on 2026-07-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_add_months_to_gym_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='theme_color',
            field=models.CharField(choices=[('blue', 'Blue'), ('emerald', 'Emerald'), ('teal', 'Teal'), ('indigo', 'Indigo'), ('violet', 'Violet'), ('rose', 'Rose'), ('orange', 'Orange')], default='blue', max_length=20),
        ),
    ]
