# Generated by Django 5.1.4 on 2026-07-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_gym_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='card_color',
            field=models.CharField(choices=[('slate', 'Slate'), ('graphite', 'Graphite'), ('stone', 'Stone'), ('navy', 'Navy'), ('forest', 'Forest'), ('plum', 'Plum'), ('wine', 'Wine')], default='slate', max_length=20),
        ),
    ]
