# Generated by Django 5.1.4 on 2026-07-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0008_gym_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='card_color',
            field=models.CharField(choices=[('slate', 'Slate'), ('graphite', 'Graphite'), ('midnight', 'Midnight'), ('navy', 'Navy'), ('indigo', 'Indigo'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('stone', 'Stone'), ('bronze', 'Bronze'), ('plum', 'Plum'), ('wine', 'Wine')], default='slate', max_length=20),
        ),
        migrations.AlterField(
            model_name='gym',
            name='theme_color',
            field=models.CharField(choices=[('rose', 'Rose'), ('red', 'Red'), ('orange', 'Orange'), ('amber', 'Amber'), ('yellow', 'Yellow'), ('lime', 'Lime'), ('green', 'Green'), ('emerald', 'Emerald'), ('teal', 'Teal'), ('cyan', 'Cyan'), ('sky', 'Sky'), ('blue', 'Blue'), ('indigo', 'Indigo'), ('violet', 'Violet'), ('purple', 'Purple'), ('fuchsia', 'Fuchsia'), ('pink', 'Pink')], default='blue', max_length=20),
        ),
    ]
