# Generated by Django 5.1.4 on 2026-07-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0009_alter_gym_card_color_alter_gym_theme_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='tier',
            field=models.CharField(choices=[('TIER1', 'Starter'), ('TIER2_WA', 'Connect'), ('TIER2_AT', 'Track'), ('TIER3', 'Elite')], default='TIER1', max_length=20),
        ),
    ]
