# Generated by Django 5.1.4 on 2026-07-14 21:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0010_alter_gym_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='whatsapp_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.60'), max_digits=6),
        ),
        migrations.CreateModel(
            name='WhatsAppBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_bills', to='gyms.gym')),
            ],
            options={
                'db_table': 'whatsapp_bills',
                'ordering': ['-period_start'],
                'unique_together': {('gym', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='WhatsAppUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RECEIPT', 'Receipt'), ('WELCOME', 'Welcome'), ('REMINDER', 'Reminder')], max_length=20)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='gyms.whatsappbill')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_usages', to='gyms.gym')),
            ],
            options={
                'db_table': 'whatsapp_usages',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['gym', 'sent_at'], name='whatsapp_us_gym_id_ef1df2_idx')],
            },
        ),
    ]
