# Generated by Django 5.1.4 on 2026-07-15 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0011_gym_whatsapp_rate_whatsappbill_whatsappusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappusage',
            name='bill',
        ),
        migrations.AddField(
            model_name='gym',
            name='wa_allowance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gym',
            name='wa_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WhatsAppTopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.PositiveIntegerField()),
                ('carried_over', models.PositiveIntegerField(default=0)),
                ('allowance_after', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_topups', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_topups', to='gyms.gym')),
            ],
            options={
                'db_table': 'whatsapp_topups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='WhatsAppBill',
        ),
        migrations.AddIndex(
            model_name='whatsapptopup',
            index=models.Index(fields=['gym', '-created_at'], name='whatsapp_to_gym_id_ecbe51_idx'),
        ),
    ]
