# Generated by Django 5.1.4 on 2026-07-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0012_remove_whatsappusage_bill_gym_wa_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappusage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappusage',
            name='error_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappusage',
            name='error_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='whatsappusage',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappusage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappusage',
            name='recipient',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappusage',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], default='SENT', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappusage',
            name='wamid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='whatsappusage',
            index=models.Index(fields=['gym', 'recipient', 'status'], name='whatsapp_us_gym_id_cb3563_idx'),
        ),
    ]
