# Generated by Django 5.1.4 on 2026-07-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0013_whatsappusage_delivered_at_whatsappusage_error_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='card_color',
            field=models.CharField(choices=[('slate', 'Slate'), ('graphite', 'Graphite'), ('midnight', 'Midnight'), ('onyx', 'Onyx'), ('navy', 'Navy'), ('indigo', 'Indigo'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('stone', 'Stone'), ('bronze', 'Bronze'), ('plum', 'Plum'), ('wine', 'Wine')], default='slate', max_length=20),
        ),
    ]
