# Generated by Django 5.1.4 on 2026-07-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0014_alter_gym_card_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='gym_backgrounds/'),
        ),
        migrations.AddField(
            model_name='gym',
            name='background_mode',
            field=models.CharField(choices=[('default', 'Default'), ('animated', 'Animated'), ('upload', 'Upload')], default='default', max_length=20),
        ),
    ]
