# Generated by Django 5.1.4 on 2026-07-21 21:36

from django.db import migrations, models


def phone_to_owner(apps, schema_editor):
    # The old `phone` was entered by the superadmin — that's really the owner
    # contact, so seed owner_phone from it. `phone` is kept as the slip phone the
    # gym can adjust from Settings.
    Gym = apps.get_model('gyms', 'Gym')
    for gym in Gym.objects.exclude(phone='').filter(owner_phone=''):
        gym.owner_phone = gym.phone
        gym.save(update_fields=['owner_phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0015_gym_background_image_gym_background_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RunPython(phone_to_owner, migrations.RunPython.noop),
    ]
