# Generated by Django 5.1.4 on 2026-07-21 22:29

from django.db import migrations, models


SEED = [
    dict(tier_id='TIER1', name='Starter', label='Tier 1', sort_order=0, recommended=False,
         description='Everything you need to run a gym',
         features=['Member management', 'Packages & subscriptions', 'Payment recording',
                   'Expenses tracking', 'Inventory management', 'Dashboard & reports',
                   'Export to Excel', 'Gender & profile filters'],
         locked=[]),
    dict(tier_id='TIER2_WA', name='Connect', label='Tier 2.1', sort_order=1, recommended=False,
         description='Starter + digital payment slips via WhatsApp',
         features=['Everything in Starter', 'WhatsApp payment slips',
                   'Digital receipt sharing', 'Member notification on payment'],
         locked=['Attendance system']),
    dict(tier_id='TIER2_AT', name='Track', label='Tier 2.2', sort_order=2, recommended=False,
         description='Starter + member attendance tracking',
         features=['Everything in Starter', 'Member check-in / check-out',
                   'Attendance reports', 'Daily attendance log'],
         locked=['WhatsApp payment slips']),
    dict(tier_id='TIER3', name='Elite', label='Tier 3', sort_order=3, recommended=True,
         description='Full package — WhatsApp + Attendance',
         features=['Everything in Starter', 'WhatsApp payment slips',
                   'Member check-in / check-out', 'Attendance reports',
                   'Daily attendance log', 'Digital receipt sharing'],
         locked=[]),
]


def seed_tiers(apps, schema_editor):
    TierInfo = apps.get_model('gyms', 'TierInfo')
    for row in SEED:
        TierInfo.objects.update_or_create(tier_id=row['tier_id'], defaults=row)


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0016_gym_owner_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_id', models.CharField(choices=[('TIER1', 'Starter'), ('TIER2_WA', 'Connect'), ('TIER2_AT', 'Track'), ('TIER3', 'Elite')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('features', models.JSONField(blank=True, default=list)),
                ('locked', models.JSONField(blank=True, default=list)),
                ('recommended', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'tier_info',
                'ordering': ['sort_order'],
            },
        ),
        migrations.RunPython(seed_tiers, migrations.RunPython.noop),
    ]
