# Generated by Django 5.1.4 on 2026-07-21 22:48

from django.db import migrations, models


COLORS = {'TIER1': 'blue', 'TIER2_WA': 'green', 'TIER2_AT': 'purple', 'TIER3': 'yellow'}


def seed_colors(apps, schema_editor):
    TierInfo = apps.get_model('gyms', 'TierInfo')
    for tier_id, color in COLORS.items():
        TierInfo.objects.filter(tier_id=tier_id).update(color=color)


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0017_tierinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tierinfo',
            name='color',
            field=models.CharField(default='blue', max_length=20),
        ),
        migrations.AlterField(
            model_name='tierinfo',
            name='tier_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.RunPython(seed_colors, migrations.RunPython.noop),
    ]
