# Generated by Django 5.1.4 on 2026-08-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0018_tierinfo_color_alter_tierinfo_tier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
