# Generated by Django 5.1.4 on 2026-07-23 21:11

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocklog_deleted_at_stocklog_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stocklog',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
