# Generated by Django 5.1.4 on 2026-07-07 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0006_add_months_to_gym_payment'),
        ('members', '0011_member_device_user_id'),
        ('trainers', '0002_trainer_device_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('DEVICE', 'Device'), ('MANUAL', 'Manual')], default='DEVICE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='gyms.gym')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='members.member')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='trainers.trainer')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-date', 'check_in'],
                'indexes': [models.Index(fields=['gym', 'date'], name='attendance_gym_id_21beff_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('member__isnull', False)), fields=('member', 'date'), name='uniq_member_day'), models.UniqueConstraint(condition=models.Q(('trainer__isnull', False)), fields=('trainer', 'date'), name='uniq_trainer_day')],
            },
        ),
    ]
