# Generated by Django 5.1.4 on 2026-07-07 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('gyms', '0006_add_months_to_gym_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('port', models.PositiveIntegerField(default=4370)),
                ('password', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=255)),
                ('last_sync_count', models.IntegerField(default=0)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_config', to='gyms.gym')),
            ],
            options={
                'db_table': 'device_config',
            },
        ),
    ]
