# Generated by Django 5.1.4 on 2026-07-25 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_deviceconfig_agent'),
        ('gyms', '0018_tierinfo_color_alter_tierinfo_tier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='live_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PUSH_USERS', 'Push members to device'), ('LIST_USERS', 'List device users'), ('ENROLL', 'Enrol a fingerprint'), ('REMOVE_FP', 'Remove a fingerprint'), ('FP_STATUS', 'Check fingerprint')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('PENDING', 'Waiting for the agent'), ('RUNNING', 'Running on the device'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_commands', to='gyms.gym')),
            ],
            options={
                'db_table': 'device_commands',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gym', 'state'], name='device_comm_gym_id_8ccfd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='LiveScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('punched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_scans', to='gyms.gym')),
            ],
            options={
                'db_table': 'live_scans',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['gym', 'id'], name='live_scans_gym_id_96ca48_idx')],
            },
        ),
    ]
