# Generated by Django 5.1.4 on 2026-07-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_device_commands_and_live_scans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecommand',
            name='kind',
            field=models.CharField(choices=[('PUSH_USERS', 'Push members to device'), ('LIST_USERS', 'List device users'), ('ENROLL', 'Enrol a fingerprint'), ('REMOVE_FP', 'Remove a fingerprint'), ('FP_STATUS', 'Check fingerprint'), ('SYNC_NOW', 'Sweep punches now')], max_length=20),
        ),
    ]
