# Generated by Django 5.1.4 on 2026-07-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_trainer_uniq_trainer_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='has_fingerprint',
            field=models.BooleanField(default=False),
        ),
    ]
