# Generated by Django 5.1.4 on 2026-07-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('BILLS', 'Bills'), ('SALARIES', 'Salaries'), ('EQUIPMENT', 'Equipment'), ('MAINTENANCE', 'Maintenance'), ('MARKETING', 'Marketing'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
