# Generated by Django 5.1.4 on 2026-07-23 21:11

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expense_deleted_at_expense_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='expense',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
