# Generated by Django 5.1.4 on 2026-07-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='has_trainer',
            field=models.BooleanField(default=False),
        ),
    ]
