# Generated by Django 5.1.4 on 2026-07-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_add_months_to_gym_payment'),
        ('members', '0004_member_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('gym', 'member_id')},
        ),
    ]
