# Generated by Django 5.1.4 on 2026-07-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_add_months_to_gym_payment'),
        ('members', '0005_add_member_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('gym', 'member_id'), ('gym', 'phone')},
        ),
    ]
