# Generated by Django 5.1.4 on 2026-07-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_add_phone_unique_per_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
