# Generated by Django 5.1.4 on 2026-07-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_add_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
