# Generated by Django 5.1.4 on 2026-07-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_member_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='reminder_sent_for',
            field=models.DateField(blank=True, null=True),
        ),
    ]
