# Generated by Django 5.1.4 on 2026-07-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_member_reminder_sent_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='device_user_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
