# Generated by Django 5.1.4 on 2026-07-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_add_months_to_gym_payment'),
        ('members', '0011_member_device_user_id'),
        ('packages', '0002_package_has_trainer'),
        ('trainers', '0002_trainer_device_user_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('device_user_id', ''), _negated=True), fields=('gym', 'device_user_id'), name='uniq_member_device_id'),
        ),
    ]
