# Generated by Django 5.1.4 on 2026-07-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_member_uniq_member_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='blacklist_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='blacklist_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='blacklisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
