# Generated by Django 5.1.4 on 2026-07-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_member_blacklist_reason_member_blacklist_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
