# Generated by Django 5.1.4 on 2026-07-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_member_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='has_fingerprint',
            field=models.BooleanField(default=False),
        ),
    ]
