# Generated by Django 5.1.4 on 2026-08-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_member_has_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dues',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('PARTIAL', 'Partial')], default='ACTIVE', max_length=20),
        ),
    ]
