# Generated by Django 5.1.4 on 2026-08-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_member_dues_alter_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dues_reminded_for',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
