# Generated by Django 5.1.4 on 2026-08-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_member_dues_reminded_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='lapsed_reminder_sent_for',
            field=models.DateField(blank=True, null=True),
        ),
    ]
