# Generated by Django 5.1.4 on 2026-07-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='new_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='prev_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
