# Generated by Django 5.1.4 on 2026-07-15 23:45

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_deleted_at_payment_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='payment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='is_rejoin',
            field=models.BooleanField(default=False),
        ),
    ]
