# Generated by Django 5.1.4 on 2026-08-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_managers_payment_is_rejoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_dues_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_joining',
            field=models.BooleanField(default=False),
        ),
    ]
