# Generated by Django 5.1.4 on 2026-08-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_admission_amount_payment_is_dues_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='dues_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
